default_language_version:
  python: python3.12

repos:
  - repo: local
    hooks:
      - id: validate
        name: validate
        entry: just validate
        language: system
        types: [python]
        pass_filenames: false
